version: '3'

services:
  dbpostgres:
    image: postgres
    ports: 
      - '5432:5432'
    container_name: gerenciador-restoque
    volumes: 
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gerenciador-restoque


volumes: 
  postgres-disk: